/* Copyright 2006 David N. Welton

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

package heclbuilder;

import java.io.File;

import javax.swing.JOptionPane;

import org.hecl.HeclException;
import org.hecl.files.HeclFile;

public class HeclEditor extends javax.swing.JFrame {

    StringBuffer script;
    File scriptfile;

    /** Creates new form HeclEditor */
    public HeclEditor() {
        initComponents();
    }

    public HeclEditor(String filename) {
        initComponents();
        scriptfile = new File(filename);
        if (scriptfile.exists()) {
            try {
                script = HeclFile.readFile(filename);
            } catch (HeclException e) {
                JOptionPane.showMessageDialog(null, "File Error", "Error reading file: " + filename + "\n" + e.toString(), JOptionPane.ERROR_MESSAGE);
            }
        } else {
            script = new StringBuffer("");
        }
        editPanel.setText(script.toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        editScrollPane = new javax.swing.JScrollPane();
        editPanel = new javax.swing.JEditorPane();
        editMenuBar1 = new javax.swing.JMenuBar();
        editMenu = new javax.swing.JMenu();
        menuSave = new javax.swing.JMenuItem();
        menuClose = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editScrollPane.setAutoscrolls(true);
        editScrollPane.setPreferredSize(null);
        editPanel.setDragEnabled(true);
        editScrollPane.setViewportView(editPanel);

        editMenu.setText("Menu");
        menuSave.setText("Save");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        menuSave.addMenuDragMouseListener(new javax.swing.event.MenuDragMouseListener() {
            public void menuDragMouseDragged(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseExited(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseReleased(javax.swing.event.MenuDragMouseEvent evt) {
                menuSaveMenuDragMouseReleased(evt);
            }
        });

        editMenu.add(menuSave);

        menuClose.setText("Close");
        menuClose.addMenuDragMouseListener(new javax.swing.event.MenuDragMouseListener() {
            public void menuDragMouseDragged(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseExited(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseReleased(javax.swing.event.MenuDragMouseEvent evt) {
                menuCloseMenuDragMouseReleased(evt);
            }
        });

        editMenu.add(menuClose);

        editMenuBar1.add(editMenu);

        setJMenuBar(editMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .add(editScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .add(editScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCloseMenuDragMouseReleased(javax.swing.event.MenuDragMouseEvent evt) {//GEN-FIRST:event_menuCloseMenuDragMouseReleased
        script = null;
        this.dispose();
    }//GEN-LAST:event_menuCloseMenuDragMouseReleased

    private void menuSaveMenuDragMouseReleased(javax.swing.event.MenuDragMouseEvent evt) {//GEN-FIRST:event_menuSaveMenuDragMouseReleased
        try {
            HeclFile.writeFile(scriptfile.toString(), editPanel.getText());
        } catch (HeclException e) {
            JOptionPane.showMessageDialog(null, "File Error", "Could not write to: " + scriptfile + "\n" + e.toString(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuSaveMenuDragMouseReleased

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_menuSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuBar editMenuBar1;
    private javax.swing.JEditorPane editPanel;
    private javax.swing.JScrollPane editScrollPane;
    private javax.swing.JMenuItem menuClose;
    private javax.swing.JMenuItem menuSave;
}
